language: node_js
node_js:
- node
- '6'
- '4'
script: npm run test-ci
deploy:
  provider: npm
  email: christopher.andrejewski@gmail.com
  on:
    tags: true
    repo: andrejewski/introspec
after_success:
- npm run coveralls
